# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyapp',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='currencyapp',
            name='given_currency',
        ),
        migrations.RemoveField(
            model_name='currencyapp',
            name='time',
        ),
        migrations.RemoveField(
            model_name='currencyapp',
            name='wanted_currency',
        ),
        migrations.AddField(
            model_name='currencyapp',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
